package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"task-manager/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, username string, email string, password string) (*model.User, error) {
	user, err := r.userSrv.CreateUser(ctx, username, email, password)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthResponse, error) {
	response, err :=r.userSrv.Login(ctx, username, password)
	if err != nil {
		return nil, err
	}
	return response, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string) (*model.Project, error) {
	project, err := r.projectSrv.CreateProject(ctx, name)
	if err != nil {
		return nil, err
	}
	return project, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, name string) (*model.Project, error) {
	uptProject, err := r.projectSrv.UpdateProject(ctx, id, name)
	if err != nil {
		return nil, err
	}
	return uptProject, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	cond, err :=r.projectSrv.DeleteProject(ctx, id)
	return cond, err
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string, projectID string) (*model.Task, error) {
	task, err := r.taskSrv.CreateTask(ctx, title, projectID)
	if err != nil {
		return nil, err
	}
	return task, nil

}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, title *string, status *string) (*model.Task, error) {
	updTask, err := r.taskSrv.UpdateTask(ctx, id, title, status)
	if err != nil {
		return nil, err
	}
	return updTask, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	cond, err := r.taskSrv.DeleteTask(ctx, id)
	return cond, err
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	projects, err := r.projectSrv.GetAllProjects(ctx)
	if err != nil {
		return nil, err
	}
	return projects, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	project, err := r.projectSrv.GetProjectByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return project, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) ProjectTasks(ctx context.Context, projectID string) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: ProjectTasks - projectTasks"))
}
*/
