// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type Project struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Owner *User   `json:"owner"`
	Tasks []*Task `json:"tasks,omitempty"`
}

type Query struct {
}

type Task struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	Project   *Project  `json:"project"`
}

type User struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Email    string     `json:"email"`
	Projects []*Project `json:"projects,omitempty"`
}
